name: Deploy to GitHub Pages
on:
  workflow_call:
    inputs:
      project-version:
        required: true
        type: string
      artifact-name:
        required: true
        type: string
      target-branch-name:
        required: false
        type: string
        default: "gh-pages"
      update-latest:
        required: false
        type: boolean
        default: false
      versioned-page:
        required: false
        type: boolean
        default: true

jobs:
  docs:
    runs-on: "ubuntu-latest"
    if: ${{ inputs.versioned-page || inputs.update-latest  }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Download Artifact
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: ${{ inputs.artifact-name }}
          path: source
      - name: Create staging directory
        run: mkdir staging
      - name: Copy to versioned page
        if: ${{ inputs.versioned-page }}
        run: cp -r source staging/${{ inputs.project-version }}
      - name: Copy to latest
        if: ${{ inputs.update-latest }}
        run: cp -r source staging/latest
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8 # v4.7.3
        with:
          branch: ${{ inputs.target-branch-name }}
          folder: staging
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: false
