name: Deploy to GitHub Pages
on:
  workflow_call:
    inputs:
      project-version:
        required: true
        type: string
      artifact-name:
        required: true
        type: string
      target-branch-name:
        required: false
        type: string
        default: "gh-pages"
      update-latest:
        required: false
        type: boolean
        default: false
      versioned-page:
        required: false
        type: boolean
        default: true

jobs:
  docs:
    runs-on: "ubuntu-latest"
    if: ${{ inputs.versioned-page || inputs.update-latest  }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Download Artifact
        uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: ${{ inputs.artifact-name }}
          path: source
      - name: Create staging directory
        run: mkdir staging
      - name: Copy to versioned page
        if: ${{ inputs.versioned-page }}
        run: cp -r source staging/${{ inputs.project-version }}
      - name: Copy to latest
        if: ${{ inputs.update-latest }}
        run: cp -r source staging/latest
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        with:
          branch: ${{ inputs.target-branch-name }}
          folder: staging
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: false
