name: Deploy to GitHub Pages
on:
  workflow_call:
    inputs:
      project-version:
        required: true
        type: string
      artifact-name:
        required: true
        type: string
      target-branch-name:
        required: false
        type: string
        default: "gh-pages"
      update-latest:
        required: false
        type: boolean
        default: false
      versioned-page:
        required: false
        type: boolean
        default: true

jobs:
  docs:
    runs-on: "ubuntu-latest"
    if: ${{ inputs.versioned-page || inputs.update-latest  }}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Download Artifact
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: ${{ inputs.artifact-name }}
          path: source
      - name: Create staging directory
        run: mkdir staging
      - name: Copy to versioned page
        if: ${{ inputs.versioned-page }}
        run: cp -r source staging/${{ inputs.project-version }}
      - name: Copy to latest
        if: ${{ inputs.update-latest }}
        run: cp -r source staging/latest
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4a3abc783e1a24aeb44c16e869ad83caf6b4cc23 # v4.7.4
        with:
          branch: ${{ inputs.target-branch-name }}
          folder: staging
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: false
